name: app_test
description: A new Flutter project.

publish_to: 'none'
version: 1.2.4

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # UI
  #  smooth_page_indicator: ^1.0.0+2
  flutter_neumorphic: ^3.2.0
  google_fonts: any
  #  ndialog: ^4.1.1
  #  loading_indicator: ^3.0.3
  #  overlay_support: ^1.2.1
  #  pinput: ^1.2.2
  #  modal_bottom_sheet: ^2.0.1
  #  custom_check_box: ^0.0.4
  #  flutter_slidable: ^1.2.0
  #  inview_notifier_list: ^3.0.0
  #  flutter_link_previewer: ^2.6.6
  #  flutter_parsed_text: ^2.2.1
  #  flutter_switch: ^0.3.2
  #  pageviewj: ^0.0.3
  #  step_progress_indicator: ^1.0.2


  # PERSISTENCE
  hive: ^2.1.0
  hive_flutter: ^1.1.0
  hive_generator: ^1.1.2


  # ARCHITECTURE
  provider: ^6.0.2
  path_provider: ^2.0.10


  #   FIREBASE
  #  firebase_messaging: ^11.3.0
  #  firebase_dynamic_links: ^4.2.2
  #  firebase_core: ^1.16.0


  # GEO
  #  google_place: ^0.4.7
  #  google_maps_flutter: ^2.1.5


  # PHOTO
  #  image_cropper: ^1.5.1
  #  image_picker: ^0.8.5
  #  stories_editor: ^0.1.8
  #
  #  photo_view: ^0.13.0
  #  pinch_zoom_image_last: ^0.4.1
  cached_network_image: ^3.2.0
  flutter_svg: ^1.0.3
  #  video_player: any
  #  video_compress_ds: ^3.1.6
  #
  #  chewie: ^1.3.2
  #  video_editor: ^1.4.1
  #  camera: ^0.9.4+21
  #  video_thumbnail: ^0.5.0
  #  flutter_native_image: ^0.0.6+1

  #  image_editor_plus:
  #    git:
  #      url: https://github.com/xande-er/image_editor_plus.git
  #      ref: 4c48792b6e95f315fe7ed76ec1c8356169c25581


  # SERVICE
  flutter_hooks: ^0.18.3
  #  responsive_framework: ^0.1.7
  #  responsive_framework: ^0.1.8
  flutter_localized_locales: ^2.0.3
  flutter_localizations:
    sdk: flutter
  #  device_info: ^2.0.3
  #  flutter_datetime_picker: ^1.5.1
  pull_to_refresh: ^2.0.0



  # CONNECT
  url_launcher: ^6.1.2

dev_dependencies:
  # PERSISTENCE
  build_runner: ^2.1.10

  flutter_lints: ^1.0.4
  flutter_test:
    sdk: flutter

flutter:
  generate: true
  uses-material-design: true
  assets:
    - picture/
    - picture/components/